name: Retype v7 Manual Preview

on:
  push:
    branches:
      - v7_manual_rework

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: retypeapp/action-build@v3
        with:
          config: retype.preview.yml

      - uses: retypeapp/action-github-pages@v3
        with:
          branch: preview-pages

